### ISSUE TITLE
Implement (advanced) Contribution Interface (MVP) missing endpoints

### ISSUE THREAD

**Issue by lutangar** [dis-moi/backend#375]
As the (Advanced) Contribution Interface project moving forward will need the following [features for the MVP](https://github.com/dis-moi/contribution-Interface/issues?q=is%3Aissue+is%3Aopen+label%3AMVP)

Are the following endpoints implemented yet @Goutte ? I
If so let's tick the boxed and the name exact name instead.
if not, we will implement the missing endpoints in this issue :
- [ ]  create a deactivated user (signup) (https://github.com/dis-moi/contribution-Interface/issues/1)
- [ ] activate a user given the right token (once its email is validated)  (https://github.com/dis-moi/contribution-Interface/issues/1)
- [ ] create a contributor for my user (https://github.com/dis-moi/contribution-Interface/issues/3)
- [ ] request a new password  for a user (when a user lost his) (see https://github.com/dis-moi/contribution-Interface/issues/6)
- [ ] logout - invalidate user token (https://github.com/dis-moi/contribution-Interface/issues/5)
- [ ] login - given i am an activated user -  (https://github.com/dis-moi/contribution-Interface/issues/2)
- [ ] Publish a notice under my "contributor account" (https://github.com/dis-moi/contribution-Interface/issues/4)
- [ ] Retrieve the list of my notices (filter notices by contributor) (https://github.com/dis-moi/contribution-Interface/issues/14)
- [ ] Retrieve the number of subscribers of a contributor  (https://github.com/dis-moi/contribution-Interface/issues/14)

**Comment by Goutte** [comment]
I can safely say that **none** of them are implemented yet in the API v4.  :3
